---
# tasks file for docker_infras_init

- name: Remove old versions
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Update cache pkg
  apt:
    name: '*'
    state: latest
    update_cache: yes

- name: Install yum required packs
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker official GPG key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo apt-key fingerprint 0EBFCD88"

- name: Set up repo
  shell: "sudo add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\""

- name: Update cache pkg
  apt:
    name: '*'
    state: latest
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user ubuntu to docker
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Install Docker-machine
  shell: "base=https://github.com/docker/machine/releases/download/v0.16.0 &&
            curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
            sudo mv /tmp/docker-machine /usr/local/bin/docker-machine &&
            chmod +x /usr/local/bin/docker-machine"

- name: Install VB driver
  apt:
    deb: https://download.virtualbox.org/virtualbox/6.1.10/virtualbox-6.1_6.1.10-138449~Ubuntu~bionic_amd64.deb

- name: Update cache pkg
  apt:
    name: '*'
    state: latest
    update_cache: yes

- name: Install Others
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - gcc
    - make
    - perl
    - dkms

- name: Restart VB driver
  shell: "sudo /sbin/vboxconfig"